apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80            # Port your app will be accessed on inside the cluster
      targetPort: 80      # Port your container listens on
      nodePort: 30080     # External port (between 30000–32767)
